In [146]:
import matplotlib.pyplot as plt
import numpy as np

In [147]:
def activation_function(x):
  mask = 1*(x >= 0)
  x = x * mask
  return x

In [152]:
class MaxNet():
    def __init__(self, diminsion, e, activation_function):
        self.diminsion = diminsion
        self.e = e
        self.activation_function = activation_function
        self.weight = np.eye(self.diminsion, dtype='float')*self.e + np.eye(self.diminsion, dtype='float') + -1 * np.ones((self.diminsion, self.diminsion), dtype='float') * self.e

    def stop_condition(self, x):
        nzeros = np.sum(1*(x == 0))
        if nzeros == (self.diminsion -1):
            return True
        return False

    def update(self, x):
        counter = 0
        print ('in iteration = {}'.format(counter + 1))
        print( x.flatten())
        print("\n")

        while True:
            x = self.activation_function(np.matmul(self.weight, x))
            counter += 1
            print ('in iteration = {}'.format(counter + 1))
            print( x.flatten())
            print("\n")
            if self.stop_condition(x) == True:
              break
        

In [153]:
x = np.array([1.2, 1.1, 1, 0.9, 0.95, 1.15]).reshape(-1, 1)
epsilon = 0.15
net = MaxNet(x.shape[0], epsilon, activation_function)
net.update(x)

in iteration = 1
[1.2  1.1  1.   0.9  0.95 1.15]


in iteration = 2
[0.435  0.32   0.205  0.09   0.1475 0.3775]


in iteration = 3
[ 0.264     0.13175  -0.       -0.       -0.        0.197875]


in iteration = 4
[ 0.21455625  0.06246875 -0.         -0.         -0.          0.1385125 ]


in iteration = 5
[ 0.18440906  0.00950844 -0.         -0.         -0.          0.09695875]


in iteration = 6
[ 0.16843898 -0.         -0.         -0.         -0.          0.06787112]


in iteration = 7
[ 0.15825832 -0.         -0.         -0.         -0.          0.04260528]


in iteration = 8
[ 0.15186752 -0.         -0.         -0.         -0.          0.01886653]


in iteration = 9
[ 0.14903754 -0.         -0.         -0.         -0.         -0.        ]


